#Author: vsankar@pch.com
@Desktop @Mobile @Sanity @RT-07723 @RT-07722
Feature: Verify SQS log entries for all the supplier's events
  In order to verify log entries
  as a user I need to select a vendor and verify ListenersLogger entries

  Scenario Outline: 1 Verify SQS events for LUCID supplier survey for test "<userType>" user
    Given I land on the Surveys Page as a "<userType>" user
    And I navigates to survey 'Auto_Lucid_Tokens'
    When I answer all basic profile questions as a "<userType>" user
    And I generate the survey endpoint url with 'complete' status
    And I call the survey endpoint url
    Then I verify SQS events in the ListenersLogger log
      | Type                          | IsTestData | ReferenceId | TransactionId | Client.DeviceType | Client.IpAddress | Source.IpAddress | Source.OriginatingUrl                                    | Source.TrackingToken | Source.CBL | Session.SessionToken | Session.MidSessionKey | Session.GaSessionId | Session.ParentMidSessionKey | Data.GMT | Data.OAT | Data.PlacementId  | Data.MidKey | Data.Page   | Data.Suppression | Data.RefererURL                                         | Data.ContestEntriesGranted | Data.Duration | Data.LengthInMinutes | Data.MinimumGrossCPI | Data.Payout | Data.Status | Data.TokensGranted    | Data.SurveyId | Data.Tokens.Complete  | Data.Tokens.Incomplete  | Data.Entries.Complete | Data.Entries.Incomplete | Data.SurveyType | Data.IsMission | Data.IsPath | Data.MidOrder | Data.MissionResetType | Data.Consent |
      | MID_START                     | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | notnull              | notnull               | notnull             |                             | fromReg  | fromReg  | Auto_Lucid_Tokens | 4HOIIL1K1O  |             |                  | https://offers.qa.pch.com/survey?mid=Auto_Lucid_Tokens  |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | OFFERWALL_IMPRESSION          | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/api/offerwall/mids             | empty                | PCHCOM     | empty                | empty                 | empty               |                             | fromReg  | fromReg  |                   |             |             |                  |                                                         |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | OFFERS_USER_STATUS            | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_Lucid_Tokens | 4HOIIL1K1O  | basic-check | Yes              | https://offers.qa.pch.com/survey?mid=Auto_Lucid_Tokens  |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | BASIC_PROFILE_DISPLAY         | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey/profile/basic           | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_Lucid_Tokens | 4HOIIL1K1O  | basic       |                  | https://offers.qa.pch.com/survey/profile/basic          |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | CONSENT_BOX_DISPLAY           | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/consent/counter | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_Lucid_Tokens | 4HOIIL1K1O  | basic       |                  | https://offers.qa.pch.com/survey/profile/basic          |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | CONSENT_RESPONSE              | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/consent         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_Lucid_Tokens | 4HOIIL1K1O  | basic       |                  | https://offers.qa.pch.com/profilebuilder/consent        |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       | Yes          |
      | PROFILEBUILDER_BASIC_PREQUALS | false      | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/submit/basic    | empty                | SURVEYSTAB | previous             | previous              | empty               |                             | fromReg  | fromReg  |                   |             |             |                  | https://offers.qa.pch.com/survey/profile/basic          |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | PROFILE_COMPLETED             | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey/profile/complete/basic  | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_Lucid_Tokens | 4HOIIL1K1O  | basic       |                  | https://offers.qa.pch.com/survey/profile/complete/basic |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       | Yes          |
      | OFFERS_USER_STATUS            | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_Lucid_Tokens | 4HOIIL1K1O  | survey      | No               | https://offers.qa.pch.com/survey?mid=Auto_Lucid_Tokens  |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | SURVEY_START                  | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_Lucid_Tokens | 4HOIIL1K1O  |             |                  | https://offers.qa.pch.com/survey/profile/basic          | 0,empty                    |             0 |                   15 |                  0.5 |           0 | empty       | 0,empty               |             0 | 5000,Desktop Complete | 5000,Desktop incomplete | 1,AW123               | 1,AW124                 | lucid           |                |             |               |                       |              |
      | SURVEY_END                    | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/surveycomplete                 | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_Lucid_Tokens | 4HOIIL1K1O  |             |                  | https://offers.qa.pch.com/surveycomplete                | 1,AW123                    |             0 |                    0 |                    0 | notnull     | complete    | 5000,Desktop Complete |       8823141 | 5000,Desktop Complete | 5000,Desktop incomplete | 1,AW123               | 1,AW124                 | lucid           |                |             |               |                       |              |

    Examples: 
      | userType |
      | full reg |

  Scenario Outline: 2 Verify SQS events for LUCID supplier survey for "<userType>" user, when launching the same mid again.
    Given I land on the Surveys Page as a "<userType>" user
    And I navigates to survey 'Auto_Lucid_Tokens'
    When I answer all basic profile questions as a "<userType>" user
    And I generate the survey endpoint url with 'complete' status
    And I call the survey endpoint url
    And I navigates to survey 'Auto_Lucid_Tokens'
    Then I verify SQS events in the ListenersLogger log
      | Type         | IsTestData | ReferenceId | TransactionId | Client.DeviceType | Client.IpAddress | Source.IpAddress | Source.OriginatingUrl                    | Source.TrackingToken | Source.CBL | Session.SessionToken | Session.MidSessionKey | Session.GaSessionId | Session.ParentMidSessionKey | Data.GMT | Data.OAT | Data.PlacementId  | Data.MidKey | Data.Page | Data.Suppression | Data.RefererURL                                        | Data.ContestEntriesGranted | Data.Duration | Data.LengthInMinutes | Data.MinimumGrossCPI | Data.Payout | Data.Status | Data.TokensGranted    | Data.SurveyId | Data.Tokens.Complete  | Data.Tokens.Incomplete  | Data.Entries.Complete | Data.Entries.Incomplete | Data.SurveyType | Data.IsMission | Data.IsPath | Data.MidOrder | Data.MissionResetType | Data.Consent |
      | MID_START    | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey         | empty                | PCHCOM     | notnull              | notnull               | notnull             |                             | fromReg  | fromReg  | Auto_Lucid_Tokens | 4HOIIL1K1O  |           |                  | https://offers.qa.pch.com/survey?mid=Auto_Lucid_Tokens |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | SURVEY_START | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_Lucid_Tokens | 4HOIIL1K1O  |           |                  | https://offers.qa.pch.com/survey                       | 0,empty                    |             0 |                   15 |                  0.5 |           0 | empty       | 0,empty               |             0 | 5000,Desktop Complete | 5000,Desktop incomplete | 1,AW123               | 1,AW124                 | lucid           |                |             |               |                       |              |
      | SURVEY_END   | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/surveycomplete | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_Lucid_Tokens | 4HOIIL1K1O  |           |                  | https://offers.qa.pch.com/surveycomplete               | 1,AW123                    |             0 |                    0 |                    0 | notnull     | complete    | 5000,Desktop Complete |       8823141 | 5000,Desktop Complete | 5000,Desktop incomplete | 1,AW123               | 1,AW124                 | lucid           |                |             |               |                       |              |
      | MID_START    | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey         | empty                | PCHCOM     | new                  | new                   | previous            |                             | fromReg  | fromReg  | Auto_Lucid_Tokens | 4HOIIL1K1O  |           |                  | https://offers.qa.pch.com/survey?mid=Auto_Lucid_Tokens |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | SURVEY_START | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey         | empty                | PCHCOM     | new                  | new                   | previous            |                             | fromReg  | fromReg  | Auto_Lucid_Tokens | 4HOIIL1K1O  |           |                  | https://offers.qa.pch.com/survey                       | 0,empty                    |             0 |                   15 |                  0.5 |           0 | empty       | 0,empty               |             0 | 5000,Desktop Complete | 5000,Desktop incomplete | 1,AW123               | 1,AW124                 | lucid           |                |             |               |                       |              |

    Examples: 
      | userType |
      | full reg |

  Scenario Outline: 3 Verify SQS events for purespectrumfusion supplier survey for "<userType>" user
    Given I land on the Surveys Page as a "<userType>" user
    And I navigates to survey 'Auto_PsFusion'
    When I answer all basic profile questions as a "<userType>" user
    And I generate the survey endpoint url with 'complete' status
    And I call the survey endpoint url
    Then I verify SQS events in the ListenersLogger log
      | Type                          | IsTestData | ReferenceId | TransactionId | Client.DeviceType | Client.IpAddress | Source.IpAddress | Source.OriginatingUrl                                    | Source.TrackingToken | Source.CBL | Session.SessionToken | Session.MidSessionKey | Session.GaSessionId | Session.ParentMidSessionKey | Data.GMT | Data.OAT | Data.PlacementId | Data.MidKey | Data.Page   | Data.Suppression | Data.RefererURL                                         | Data.ContestEntriesGranted | Data.Duration | Data.LengthInMinutes | Data.MinimumGrossCPI | Data.Payout | Data.Status | Data.TokensGranted    | Data.SurveyId | Data.Tokens.Complete  | Data.Tokens.Incomplete  | Data.Entries.Complete | Data.Entries.Incomplete | Data.SurveyType    | Data.IsMission | Data.IsPath | Data.MidOrder | Data.MissionResetType | Data.Consent |
      | MID_START                     | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | notnull              | notnull               | notnull             |                             | fromReg  | fromReg  | Auto_PsFusion    | G54NHIMKK1  |             |                  | https://offers.qa.pch.com/survey?mid=Auto_PsFusion      |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       |              |
      | OFFERWALL_IMPRESSION          | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/api/offerwall/mids             | empty                | PCHCOM     | empty                | empty                 | empty               |                             | fromReg  | fromReg  |                  |             |             |                  |                                                         |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       |              |
      | OFFERS_USER_STATUS            | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_PsFusion    | G54NHIMKK1  | basic-check | Yes              | https://offers.qa.pch.com/survey?mid=Auto_PsFusion      |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       |              |
      | BASIC_PROFILE_DISPLAY         | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey/profile/basic           | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_PsFusion    | G54NHIMKK1  | basic       |                  | https://offers.qa.pch.com/survey/profile/basic          |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       |              |
      | CONSENT_BOX_DISPLAY           | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/consent/counter | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_PsFusion    | G54NHIMKK1  | basic       |                  | https://offers.qa.pch.com/survey/profile/basic          |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       |              |
      | CONSENT_RESPONSE              | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/consent         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_PsFusion    | G54NHIMKK1  | basic       |                  | https://offers.qa.pch.com/profilebuilder/consent        |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       | Yes          |
      | PROFILEBUILDER_BASIC_PREQUALS | false      | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/submit/basic    | empty                | SURVEYSTAB | previous             | previous              | empty               |                             | fromReg  | fromReg  |                  |             |             |                  | https://offers.qa.pch.com/survey/profile/basic          |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       |              |
      | PROFILE_COMPLETED             | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey/profile/complete/basic  | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_PsFusion    | G54NHIMKK1  | basic       |                  | https://offers.qa.pch.com/survey/profile/complete/basic |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       | Yes          |
      | OFFERS_USER_STATUS            | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_PsFusion    | G54NHIMKK1  | survey      | No               | https://offers.qa.pch.com/survey?mid=Auto_PsFusion      |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       |              |
      | SURVEY_START                  | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_PsFusion    | G54NHIMKK1  |             |                  | https://offers.qa.pch.com/survey/profile/basic          | 0,empty                    |             0 |                   15 |                  0.5 |           0 | empty       | 0,empty               |             0 | 5000,Desktop Complete | 5000,Desktop incomplete | 1,AW123               | 1,AW124                 | purespectrumfusion |                |             |               |                       |              |
      | SURVEY_END                    | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/surveycomplete                 | empty                | PCHCOM     | previous             | previous              | new                 |                             | fromReg  | fromReg  | Auto_PsFusion    | G54NHIMKK1  |             |                  | https://offers.qa.pch.com/surveycomplete                | 1,AW123                    |             0 |                    0 |                    0 | notnull     | complete    | 5000,Desktop Complete |               | 5000,Desktop Complete | 5000,Desktop incomplete | 1,AW123               | 1,AW124                 | purespectrumfusion |                |             |               |                       |              |

    Examples: 
      | userType |
      | full reg |

  @RT-07768
  Scenario Outline: 4 Verify SQS events for PSFusionAPI supplier survey for "<userType>" user
    Given I land on the Surveys Page as a "<userType>" user
    And I navigates to survey 'Auto_PSplacement'
    When I answer all basic profile questions as a "<userType>" user
    And I generate the survey endpoint url with 'complete' status
    And I call the survey endpoint url
    Then I verify SQS events in the ListenersLogger log
      | Type                          | IsTestData | ReferenceId | TransactionId | Client.DeviceType | Client.IpAddress | Source.IpAddress | Source.OriginatingUrl                                    | Source.TrackingToken | Source.CBL | Session.SessionToken | Session.MidSessionKey | Session.GaSessionId | Session.ParentMidSessionKey | Data.GMT | Data.OAT | Data.PlacementId | Data.MidKey | Data.Page   | Data.Suppression | Data.RefererURL                                         | Data.ContestEntriesGranted | Data.Duration | Data.LengthInMinutes | Data.MinimumGrossCPI | Data.Payout | Data.Status | Data.TokensGranted    | Data.SurveyId | Data.Tokens.Complete  | Data.Tokens.Incomplete  | Data.Entries.Complete | Data.Entries.Incomplete | Data.SurveyType    | Data.IsMission | Data.IsPath | Data.MidOrder | Data.MissionResetType | Data.Consent |
      | MID_START                     | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | notnull              | notnull               | notnull             |                             | fromReg  | fromReg  | Auto_PSplacement | 5JHGPII35J  |             |                  | https://offers.qa.pch.com/survey?mid=Auto_PSplacement   |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       |              |
      | OFFERWALL_IMPRESSION          | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/api/offerwall/mids             | empty                | PCHCOM     | empty                | empty                 | empty               |                             | fromReg  | fromReg  |                  |             |             |                  |                                                         |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       |              |
      | OFFERS_USER_STATUS            | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_PSplacement | 5JHGPII35J  | basic-check | Yes              | https://offers.qa.pch.com/survey?mid=Auto_PSplacement   |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       |              |
      | BASIC_PROFILE_DISPLAY         | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey/profile/basic           | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_PSplacement | 5JHGPII35J  | basic       |                  | https://offers.qa.pch.com/survey/profile/basic          |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       |              |
      | CONSENT_BOX_DISPLAY           | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/consent/counter | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_PSplacement | 5JHGPII35J  | basic       |                  | https://offers.qa.pch.com/survey/profile/basic          |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       |              |
      | CONSENT_RESPONSE              | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/consent         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_PSplacement | 5JHGPII35J  | basic       |                  | https://offers.qa.pch.com/profilebuilder/consent        |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       | Yes          |
      | PROFILEBUILDER_BASIC_PREQUALS | false      | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/submit/basic    | empty                | SURVEYSTAB | previous             | previous              | empty               |                             | fromReg  | fromReg  |                  |             |             |                  | https://offers.qa.pch.com/survey/profile/basic          |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       |              |
      | PROFILE_COMPLETED             | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey/profile/complete/basic  | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_PSplacement | 5JHGPII35J  | basic       |                  | https://offers.qa.pch.com/survey/profile/complete/basic |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       | Yes          |
      | OFFERS_USER_STATUS            | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_PSplacement | 5JHGPII35J  | survey      | No               | https://offers.qa.pch.com/survey?mid=Auto_PSplacement   |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                    |                |             |               |                       |              |
      | SURVEY_START                  | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_PSplacement | 5JHGPII35J  |             |                  | https://offers.qa.pch.com/survey/profile/basic          | 0,empty                    |             0 |                   20 |                  0.5 |           0 | empty       | 0,empty               |             0 | 5000,Desktop Complete | 5000,Desktop incomplete | 1,AW123               | 1,AW124                 | purespectrumfusion |                |             |               |                       |              |
      | SURVEY_END                    | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/surveycomplete                 | empty                | PCHCOM     | previous             | previous              | notnull             |                             | fromReg  | fromReg  | Auto_PSplacement | 5JHGPII35J  |             |                  | https://offers.qa.pch.com/surveycomplete                | 1,AW123                    |               |                    0 |                    0 | notnull     | complete    | 5000,Desktop Complete |               | 5000,Desktop Complete | 5000,Desktop incomplete | 1,AW123               | 1,AW124                 | purespectrumfusion |                |             |               |                       |              |
      | FUSION_REQUEST                | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_PSplacement | 5JHGPII35J  |             |                  | https://offers.qa.pch.com/survey?mid=Auto_PSplacement   |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         | purespectrumfusion |                |             |               |                       |              |
      | SRE_MATCH_REQUEST             | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_PSplacement | 5JHGPII35J  |             |                  | https://offers.qa.pch.com/survey?mid=Auto_PSplacement   |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         | purespectrumfusion |                |             |               |                       |              |

    Examples: 
      | userType |
      | full reg |

  Scenario Outline: 5 Verify SQS events for GRL supplier survey for "<userType>" user
    Given I land on the Surveys Page as a "<userType>" user
    And I navigates to survey 'Auto_GRL'
    When I answer all basic profile questions as a "<userType>" user
    And I generate the GRL survey endpoint url with 'complete' status
    And I call the survey endpoint url
    Then I verify SQS events in the ListenersLogger log
      | Type                          | IsTestData | ReferenceId | TransactionId | Client.DeviceType | Client.IpAddress | Source.IpAddress | Source.OriginatingUrl                                    | Source.TrackingToken | Source.CBL | Session.SessionToken | Session.MidSessionKey | Session.GaSessionId | Session.ParentMidSessionKey | Data.GMT | Data.OAT | Data.PlacementId | Data.MidKey | Data.Page   | Data.Suppression | Data.RefererURL                                         | Data.ContestEntriesGranted | Data.Duration | Data.LengthInMinutes | Data.MinimumGrossCPI | Data.Payout | Data.Status | Data.TokensGranted    | Data.SurveyId | Data.Tokens.Complete  | Data.Tokens.Incomplete  | Data.Entries.Complete | Data.Entries.Incomplete | Data.SurveyType | Data.IsMission | Data.IsPath | Data.MidOrder | Data.MissionResetType | Data.Consent |
      | MID_START                     | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | notnull              | notnull               | notnull             |                             | fromReg  | fromReg  | Auto_GRL         | OK1ML3OIOO  |             |                  | https://offers.qa.pch.com/survey?mid=Auto_GRL           |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | OFFERWALL_IMPRESSION          | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/api/offerwall/mids             | empty                | PCHCOM     | empty                | empty                 | empty               |                             | fromReg  | fromReg  |                  |             |             |                  |                                                         |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | OFFERS_USER_STATUS            | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_GRL         | OK1ML3OIOO  | basic-check | Yes              | https://offers.qa.pch.com/survey?mid=Auto_GRL           |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | BASIC_PROFILE_DISPLAY         | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey/profile/basic           | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_GRL         | OK1ML3OIOO  | basic       |                  | https://offers.qa.pch.com/survey/profile/basic          |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | CONSENT_BOX_DISPLAY           | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/consent/counter | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_GRL         | OK1ML3OIOO  | basic       |                  | https://offers.qa.pch.com/survey/profile/basic          |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | CONSENT_RESPONSE              | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/consent         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_GRL         | OK1ML3OIOO  | basic       |                  | https://offers.qa.pch.com/profilebuilder/consent        |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       | Yes          |
      | PROFILEBUILDER_BASIC_PREQUALS | false      | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/submit/basic    | empty                | SURVEYSTAB | previous             | previous              | empty               |                             | fromReg  | fromReg  |                  |             |             |                  | https://offers.qa.pch.com/survey/profile/basic          |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | PROFILE_COMPLETED             | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey/profile/complete/basic  | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_GRL         | OK1ML3OIOO  | basic       |                  | https://offers.qa.pch.com/survey/profile/complete/basic |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       | Yes          |
      | OFFERS_USER_STATUS            | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_GRL         | OK1ML3OIOO  | survey      | No               | https://offers.qa.pch.com/survey?mid=Auto_GRL           |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | SURVEY_START                  | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_GRL         | OK1ML3OIOO  |             |                  | https://offers.qa.pch.com/survey/profile/basic          | 0,empty                    |             0 |                   20 |                  0.5 |           0 | empty       | 0,empty               |             0 | 5000,Desktop Complete | 5000,Desktop incomplete | 1,AW123               | 1,AW124                 | generalresearch |                |             |               |                       |              |
      | SURVEY_END                    | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/surveycomplete                 | empty                | PCHCOM     | previous             | previous              | notnull             |                             | fromReg  | fromReg  | Auto_GRL         | OK1ML3OIOO  |             |                  | https://offers.qa.pch.com/surveycomplete                | 1,AW123                    |               |                    0 |                    0 | notnull     | complete    | 5000,Desktop Complete |               | 5000,Desktop Complete | 5000,Desktop incomplete | 1,AW123               | 1,AW124                 | generalresearch |                |             |               |                       |              |

    Examples: 
      | userType |
      | full reg |

  Scenario Outline: 6 Verify SQS event for LUCIDAPI supplier survey for "<userType>" user
    Given I land on the Surveys Page as a "<userType>" user
    When I insert all basic profile questions and answers into Redis DB
    And I navigates to survey 'Auto_VinLucidApiTokens'
    When I answer all basic profile questions as a "<userType>" user
    And I generate the survey endpoint url with 'complete' status
    And I call the survey endpoint url
    Then I verify SQS events in the ListenersLogger log
      | Type                          | IsTestData | ReferenceId | TransactionId | Client.DeviceType | Client.IpAddress | Source.IpAddress | Source.OriginatingUrl                                    | Source.TrackingToken | Source.CBL | Session.SessionToken | Session.MidSessionKey | Session.GaSessionId | Session.ParentMidSessionKey | Data.GMT | Data.OAT | Data.PlacementId       | Data.MidKey | Data.Page   | Data.Suppression | Data.RefererURL                                             | Data.ContestEntriesGranted | Data.Duration | Data.LengthInMinutes | Data.MinimumGrossCPI | Data.Payout | Data.Status | Data.TokensGranted    | Data.SurveyId | Data.Tokens.Complete  | Data.Tokens.Incomplete  | Data.Entries.Complete | Data.Entries.Incomplete | Data.SurveyType | Data.IsMission | Data.IsPath | Data.MidOrder | Data.MissionResetType | Data.Consent |
      | MID_START                     | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | notnull              | notnull               | notnull             |                             | fromReg  | fromReg  | Auto_VinLucidApiTokens | KKG3G11L1K  |             |                  | https://offers.qa.pch.com/survey?mid=Auto_VinLucidApiTokens |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | OFFERWALL_IMPRESSION          | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/api/offerwall/mids             | empty                | PCHCOM     | empty                | empty                 | empty               |                             | fromReg  | fromReg  |                        |             |             |                  |                                                             |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | OFFERS_USER_STATUS            | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_VinLucidApiTokens | KKG3G11L1K  | basic-check | Yes              | https://offers.qa.pch.com/survey?mid=Auto_VinLucidApiTokens |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | BASIC_PROFILE_DISPLAY         | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey/profile/basic           | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_VinLucidApiTokens | KKG3G11L1K  | basic       |                  | https://offers.qa.pch.com/survey/profile/basic              |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | CONSENT_BOX_DISPLAY           | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/consent/counter | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_VinLucidApiTokens | KKG3G11L1K  | basic       |                  | https://offers.qa.pch.com/survey/profile/basic              |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | CONSENT_RESPONSE              | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/consent         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_VinLucidApiTokens | KKG3G11L1K  | basic       |                  | https://offers.qa.pch.com/profilebuilder/consent            |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       | Yes          |
      | PROFILEBUILDER_BASIC_PREQUALS | false      | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/submit/basic    | empty                | SURVEYSTAB | previous             | previous              | empty               |                             | fromReg  | fromReg  |                        |             |             |                  | https://offers.qa.pch.com/survey/profile/basic              |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | PROFILE_COMPLETED             | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey/profile/complete/basic  | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_VinLucidApiTokens | KKG3G11L1K  | basic       |                  | https://offers.qa.pch.com/survey/profile/complete/basic     |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       | Yes          |
      | OFFERS_USER_STATUS            | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_VinLucidApiTokens | KKG3G11L1K  | survey      | No               | https://offers.qa.pch.com/survey?mid=Auto_VinLucidApiTokens |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      | SURVEY_START                  | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_VinLucidApiTokens | KKG3G11L1K  |             |                  | https://offers.qa.pch.com/survey/profile/basic              | 0,empty                    |             0 |                   20 |                  0.5 |           0 | empty       | 0,empty               |             0 | 5000,Desktop Complete | 5000,Desktop incomplete | 1,AW123               | 1,AW124                 | lucid           |                |             |               |                       |              |
      | SURVEY_END                    | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/surveycomplete                 | empty                | PCHCOM     | previous             | previous              | notnull             |                             | fromReg  | fromReg  | Auto_VinLucidApiTokens | KKG3G11L1K  |             |                  | https://offers.qa.pch.com/surveycomplete                    | 1,AW123                    |               |                    0 |                    0 | notnull     | complete    | 5000,Desktop Complete |               | 5000,Desktop Complete | 5000,Desktop incomplete | 1,AW123               | 1,AW124                 | lucid           |                |             |               |                       |              |

    Examples: 
      | userType |
      | full reg |
      
  #Scenario Outline: 7 Verify SQS event for QMEE supplier survey for "<userType>" user
    #Given I land on the Surveys Page as a "<userType>" user
    #And I navigates to survey 'Auto_VinQmeeTokens'
    #And I answer all basic profile questions as a "<userType>" user
    #When I generate the QMEE survey endpoint url with 'complete' status
    #And I call the survey endpoint url
    #Then I verify SQS events in the ListenersLogger log
      #| Type                          | IsTestData | ReferenceId | TransactionId | Client.DeviceType | Client.IpAddress | Source.IpAddress | Source.OriginatingUrl                                    | Source.TrackingToken | Source.CBL | Session.SessionToken | Session.MidSessionKey | Session.GaSessionId | Session.ParentMidSessionKey | Data.GMT | Data.OAT | Data.PlacementId   | Data.MidKey | Data.Page   | Data.Suppression | Data.RefererURL                                         | Data.ContestEntriesGranted | Data.Duration | Data.LengthInMinutes | Data.MinimumGrossCPI | Data.Payout | Data.Status | Data.TokensGranted    | Data.SurveyId | Data.Tokens.Complete  | Data.Tokens.Incomplete  | Data.Entries.Complete | Data.Entries.Incomplete | Data.SurveyType | Data.IsMission | Data.IsPath | Data.MidOrder | Data.MissionResetType | Data.Consent |
      #| MID_START                     | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | notnull              | notnull               | notnull             |                             | fromReg  | fromReg  | Auto_VinQmeeTokens | NJ2LK6PJLH  |             |                  | https://offers.qa.pch.com/survey?mid=Auto_VinQmeeTokens |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      #| OFFERWALL_IMPRESSION          | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/api/offerwall/mids             | empty                | PCHCOM     | empty                | empty                 | empty               |                             | fromReg  | fromReg  |                    |             |             |                  |                                                         |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      #| OFFERS_USER_STATUS            | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_VinQmeeTokens | NJ2LK6PJLH  | basic-check | Yes              | https://offers.qa.pch.com/survey?mid=Auto_VinQmeeTokens |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      #| BASIC_PROFILE_DISPLAY         | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey/profile/basic           | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_VinQmeeTokens | NJ2LK6PJLH  | basic       |                  | https://offers.qa.pch.com/survey/profile/basic          |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      #| CONSENT_BOX_DISPLAY           | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/consent/counter | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_VinQmeeTokens | NJ2LK6PJLH  | basic       |                  | https://offers.qa.pch.com/survey/profile/basic          |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      #| CONSENT_RESPONSE              | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/consent         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_VinQmeeTokens | NJ2LK6PJLH  | basic       |                  | https://offers.qa.pch.com/profilebuilder/consent        |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       | Yes          |
      #| PROFILEBUILDER_BASIC_PREQUALS | false      | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/profilebuilder/submit/basic    | empty                | SURVEYSTAB | previous             | previous              | empty               |                             | fromReg  | fromReg  |                    |             |             |                  | https://offers.qa.pch.com/survey/profile/basic          |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      #| PROFILE_COMPLETED             | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey/profile/complete/basic  | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_VinQmeeTokens | NJ2LK6PJLH  | basic       |                  | https://offers.qa.pch.com/survey/profile/complete/basic |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       | Yes          |
      #| OFFERS_USER_STATUS            | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_VinQmeeTokens | NJ2LK6PJLH  | survey      | No               | https://offers.qa.pch.com/survey?mid=Auto_VinQmeeTokens |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         |                 |                |             |               |                       |              |
      #| SURVEY_START                  | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_VinQmeeTokens | NJ2LK6PJLH  |             |                  | https://offers.qa.pch.com/survey/profile/basic          | 0,empty                    |             0 |                   20 |                  0.5 |           0 | empty       | 0,empty               |             0 | 5000,Desktop Complete | 5000,Desktop incomplete | 1,AW123               | 1,AW124                 | qmee            |                |             |               |                       |              |
      #| SURVEY_END                    | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/surveycomplete                 | empty                | PCHCOM     | previous             | previous              | notnull             |                             | fromReg  | fromReg  | Auto_VinQmeeTokens | NJ2LK6PJLH  |             |                  | https://offers.qa.pch.com/surveycomplete                | 1,AW123                    |               |                    0 |                    0 | notnull     | complete    | 5000,Desktop Complete |               | 5000,Desktop Complete | 5000,Desktop incomplete | 1,AW123               | 1,AW124                 | qmee            |                |             |               |                       |              |
      #| QMEE_REQUEST                  | true       | notnull     | notnull       | DESKTOP           | notnull          | notnull          | https://offers.qa.pch.com/survey                         | empty                | PCHCOM     | previous             | previous              | previous            |                             | fromReg  | fromReg  | Auto_VinQmeeTokens | NJ2LK6PJLH  |             |                  | https://offers.qa.pch.com/survey?mid=Auto_VinQmeeTokens |                            |               |                      |                      |             |             |                       |               |                       |                         |                       |                         | qmee            |                |             |               |                       |              |
#
    #Examples: 
      #| userType |
      #| full reg |
