package com.pch.survey.utilities;

import java.util.UUID;

public class RandomDataGenerator {
	private static String autoGenerated;
	
	public static String getRandomEmail(){
		UUID uuid = UUID.randomUUID();
		String randomUUIDString = uuid.toString().substring(0, 15);
		autoGenerated = "pol." + randomUUIDString + DateUtilities.getOnlyTodaysDate() + "@pchmail.com";
		return autoGenerated;
		
	}
	
	public static String getAutoGeneratedEmail(){
		return autoGenerated;
	}

	

	public static String autoGenerateName(){
 		return firstCharUppercase((org.apache.commons.lang.RandomStringUtils.randomAlphabetic(15)).replaceAll("f", "z").replaceAll("F", "Z"));
		
		}

	private static String firstCharUppercase(String name) {
		return Character.toString(name.charAt(0)).toUpperCase()
				+ name.substring(1);
	}
	
}
